import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  env: {
    AUTH_URL: process.env.AUTH_URL,
    AUTH_SECRET: process.env.AUTH_SECRET,
    NEXT_PRIVATE_FIREBASE_API_KEY: process.env.NEXT_PRIVATE_FIREBASE_API_KEY,
    NEXT_PRIVATE_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PRIVATE_FIREBASE_AUTH_DOMAIN,
    NEXT_PRIVATE_FIREBASE_DATABASE_URL: process.env.NEXT_PRIVATE_FIREBASE_DATABASE_URL,
    NEXT_PRIVATE_FIREBASE_PROJECT_ID: process.env.NEXT_PRIVATE_FIREBASE_PROJECT_ID,
    NEXT_PRIVATE_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PRIVATE_FIREBASE_STORAGE_BUCKET,
    NEXT_PRIVATE_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PRIVATE_FIREBASE_MESSAGING_SENDER_ID,
    NEXT_PRIVATE_FIREBASE_APP_ID: process.env.NEXT_PRIVATE_FIREBASE_APP_ID,
  },
};

export default nextConfig;
